# Generated by Django 3.2.7 on 2022-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_regiondataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
