# Generated by Django 3.2.7 on 2022-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
