# Generated by Django 3.2.7 on 2022-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscribedusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
