# Generated by Django 3.2.7 on 2022-04-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_state_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='price',
        ),
    ]
